### ISSUE TITLE
JS environment process variable

### ISSUE THREAD

**Issue by kenny26** [ryanelian/instapack#143]
Hello, I'm a bit confused on how to set environment variable to be used on client/index.ts like so
```
// client/index.ts
const apiUrl = process.env.API_URL
```

I have tried running ipack with [cross-env](https://github.com/kentcdodds/cross-env) like
```
cross-env API_URL=localhost:3000 ipack --dev
```
also with [dotenv](https://github.com/motdotla/dotenv), but process.env remains an empty object..

So.. how can I attach config variable to client JS file using ipack?

**Comment by ryanelian** [comment]
Hello kenny!

Sorry for the trouble, but instapack *did* not support custom environment variables.
(Our team usually puts configuration in a TS module which gets imported everywhere; simpler.)

However, I understand your concern and the use case for this feature.

[I have implemented `.env` file support in instapack using `dotenv` module.](https://github.com/ryanelian/instapack#env) I hope you find this feature useful!

### .env

```env
API_URL=localhost:3000
```

### index.ts

```ts
const apiUrl = process.env.API_URL
// no need to use cross-env or dotenv within app anymore!
```

You can use this feature immediately with the beta distro: `yarn global install instapack@beta` or `npm install -g instapack@beta`

I hope this new feature solves your problem. Please close the issue if your problem was solved and don't forget to ⭐️ the repo ;)

**Comment by kenny26** [comment]
Hello, sorry for the super late reply..

Currently using the 6.4-beta7 and it's working perfectly! Thank you for your super fast response!

If I can suggest feature for next version, multiple output css bundle and JS is useful in my opinion.. For example, if your project consist of "front" page section, and "back" page like dashboard section after authenticated, it is useful to have 2 different css and js bundle.

**Comment by ryanelian** [comment]
The issue about multiple bundle is covered in README FAQ, but I'll explain again anyway.

The topic about multiple entry / multiple output has always been a hot debate within our development team.

We ended up not supporting it because:

- Each project can have vastly different `tsconfig.json` and `package.json`

- JavaScript is single-threaded. Therefore, multiple bundles will be built in **serial**, not **parallel**.

- If an entry point happened to import a module being imported by another, all hell broke loose: either both entry point will be big, or common artifacts which required by both bundles will be produced. **(Inconsistent output)**

- You generally don't want one front-end project to screw with another front-end project. Bad things happen when you make two projects using one build.

## Solution

We actually recommend you to eject multiple front-end-projects from the back-end project:

```
├───backend
│   └───wwwroot
│       ├───css
│       │       frontend1.css
│       │       frontend2.css
│       │       
│       └───js
│               frontend1.dll.js
│               frontend1.js
│               frontend2.dll.js
│               frontend2.js
│               
├───frontend1
│   │   package.json
│   │   tsconfig.json
│   │   yarn.lock
│   │   
│   └───client
│       ├───css
│       │       index.scss
│       │       
│       └───js
│               index.ts
│               
└───frontend2
    │   package.json
    │   tsconfig.json
    │   yarn.lock
    │   
    └───client
        ├───css
        │       index.scss
        │       
        └───js
                index.ts
```

### frontend1 package.json

```json
{
  "name": "aspnet",
  "version": "1.0.0",
  "private": true,
  "instapack": {
    "jsOut": "frontend1",
    "cssOut": "frontend1",
    "output": "../backend/wwwroot",
    "concat": {}
  },
  "dependencies": {
  }
}

```

### frontend2 package.json

```json
{
  "name": "aspnet",
  "version": "1.0.0",
  "private": true,
  "instapack": {
    "jsOut": "frontend2",
    "cssOut": "frontend2",
    "output": "../backend/wwwroot",
    "concat": {}
  },
  "dependencies": {
  }
}
```

## This is far cleaner and safer compared to multiple entry

Because both projects are isolated and will not screw around with each other's settings, modules and dependencies.

## What about libraries (.dll scripts) being downloaded twice?

While it looks like the weakness of the technique in a glance, we actually think that this is the strength of *project-eject* technique:

- You can have the first project using a library of certain version, while the other project using a library of another version.

- If you really need to conserve bandwidth, [externalize the modules using CDN](https://github.com/ryanelian/instapack#configurations).
