### ISSUE TITLE
Map file not created on debug watch and hot reload mode

### ISSUE THREAD

**Issue by evanemelga** [ryanelian/instapack#256]
On Instapack 7.0, when we use -dw or -h flag, the JS .map files won't be created.
Debug flag alone or watch flag alone works though.

**Comment by ryanelian** [comment]
Thank you for the bug report. **However this is not a bug.**

-dw and -h flags uses Eval Source Map which allows fast inline source mapping during development time with incremental compilation turned on.

-dw

![image](https://user-images.githubusercontent.com/8892187/46919264-175b2d80-d007-11e8-8435-0fc10ec2c55d.png)

![image](https://user-images.githubusercontent.com/8892187/46919275-42458180-d007-11e8-80ed-aa03cca6f16a.png)

Compare the output with -dwb, which entirely disables the source map: (Less build size due to the absence of inlined source map)

![image](https://user-images.githubusercontent.com/8892187/46919284-6ef99900-d007-11e8-9d3a-2bb5a0959da7.png)
