### ISSUE TITLE
Bootstrap in Node Modules Error (for version 7.3.0)

### ISSUE THREAD

**Issue by dhimasdewanto** [ryanelian/instapack#397]
./node_modules/bootstrap-vue/dist/bootstrap-vue.css 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @charset "UTF-8";
| /*!
|  * BootstrapVue Custom CSS (https://bootstrap-vue.js.org)
 @ ./client/js/vue-project.ts 13:0-46
 @ ./client/js/index.ts
 @ multi ./client/js/index.ts

./node_modules/bootstrap/dist/css/bootstrap.css 7:0
Module parse failed: Unexpected token (7:0)
You may need an appropriate loader to handle this file type.
|  * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
|  */
> :root {
|   --blue: #007bff;
|   --indigo: #6610f2;
 @ ./client/js/vue-project.ts 12:0-42
 @ ./client/js/index.ts
 @ multi ./client/js/index.ts

**Comment by ryanelian** [comment]
Thank you for the report.

Did you import the CS directly from JS or did you import the bootstrap-vue JS?

(Which one is your code?)

**Comment by dhimasdewanto** [comment]
Used npm install

**Comment by ryanelian** [comment]
I mean, what is your **TypeScript** code used to import bootstrap-vue?

**Comment by ryanelian** [comment]
Received source code via private message. Basically, CSS modules were imported directly through TypeScript, which **WAS NOT A SUPPORTED USE CASE** and was a side effect of `.vue` integration:

```ts
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue/dist/bootstrap-vue.css';
```

This is not ideal because the CSS will be embedded in JS as plain text and will not be auto-prefixed and minified!

The remedy is to import the files through Sass, which is the supported use case for instapack:

```scss
@import "bootstrap";
@import "bootstrap-vue";
```

Closing the issue.
