### ISSUE TITLE
Keep Getting "[WDS] Disconnected!" Error

### ISSUE THREAD

**Issue by Tieantono** [ryanelian/instapack#474]
Hi there, I have an issue when using your hot reload feature on an application that running using HTTPS, I keep getting "[WDS] Disconnected!" error. However, this problem does not occur when my application does not running using HTTP.

This is what it looks like in Google Chrome's DevTools:
![image](https://user-images.githubusercontent.com/14927392/62819717-3cff8780-bb83-11e9-9958-b004332a2b76.png)

**Comment by ryanelian** [comment]
I believe this is caused by the Webpack Dev Server (WDS) not running on the HTTPS port (https://localhost:28080), only the HTTP port (http://localhost:28080).

Honestly, this is a tricky problem to solve because enabling HTTPS would require a valid HTTPS certificate, which will cause the browser to show invalid certificate error (because localhost certificates are self-signed).

**Comment by ryanelian** [comment]
![image](https://user-images.githubusercontent.com/8892187/63009666-1efd9400-beaf-11e9-9e07-ee274fe65dec.png)

What happens when you enable https access for WDS.

>
>
> Turns out my issue was because I was running code on https and when I request something from webpack dev server it runs the socket code and uses whatever level of security is currently being used (in my case https). All I had to do was set https: true and it worked like a charm.

^ quoted from someone with similar problem

**Comment by Tieantono** [comment]
I see, so we have to use HTTP instead.

Thank you for your confirmation.

I'm closing this issue since it is coming from WDS.
